$ sqlplus / as sysdba

$  select * from v$version;


-- oracle connection details 
username: sys as sysdba
password: welcome 
database : xe
PORT: 1521


--table DDL 

CREATE TABLE  AAP_WELCOME_GENERIC
(
   AAP_WELCOME_TNO  NUMBER    GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 100 INCREMENT BY 1,
   ENAME      VARCHAR (10),
   JOB        VARCHAR (9),
   MGR        NUMBER,
   SAL        NUMBER,
   COMM       NUMBER,
   AAP_DEPT_TNO     NUMBER,
   file1_f1 int not null,
   file1_f2 varchar(60) not null,
   file1_f3 varchar(60) not null,
   file2_f1 int not null,
   file2_f2 varchar(60) not null,
   file2_f3 varchar(60) not null,
   file3_f1 int not null,
   file3_f2 varchar(60) not null,
   file3_f3 varchar(60) not null
)

-- SELECT QUERY
SELECT * FROM AAP_WELCOME_GENERIC;
